// ===================================================
// SURPRISE ME — 20 Template Definitions
// ===================================================

export const TEMPLATES = [
  {
    id: 'romantic',
    name: 'Love Letter',
    nameTh: 'จดหมายรัก',
    category: 'love',
    categoryTh: 'ความรัก',
    desc: 'จดหมายรักดิจิทัล เต็มไปด้วยความรู้สึกจากหัวใจ',
    icon: 'favorite',
    from: '#FF3366', to: '#9333EA',
    bg: '#0d0010',
    particle: 'hearts',
  },
  {
    id: 'birthday',
    name: 'Birthday Bash',
    nameTh: 'วันเกิดสุดอลัง',
    category: 'birthday',
    categoryTh: 'วันเกิด',
    desc: 'ฉลองวันเกิดสุดอลังการ พร้อมพลุและสีสัน',
    icon: 'celebration',
    from: '#F59E0B', to: '#EC4899',
    bg: '#0d0008',
    particle: 'confetti',
  },
  {
    id: 'anniversary',
    name: 'Anniversary',
    nameTh: 'ครบรอบคู่รัก',
    category: 'love',
    categoryTh: 'ความรัก',
    desc: 'ฉลองครบรอบวันพิเศษที่ทั้งสองคนรอคอย',
    icon: 'diamond',
    from: '#D4AF37', to: '#C2185B',
    bg: '#0d0a00',
    particle: 'petals',
  },
  {
    id: 'friendship',
    name: 'Best Friends',
    nameTh: 'เพื่อนรักตลอดไป',
    category: 'friendship',
    categoryTh: 'มิตรภาพ',
    desc: 'บอกให้เพื่อนรู้ว่าคุณคิดถึงและห่วงใยเขา',
    icon: 'handshake',
    from: '#F97316', to: '#FBBF24',
    bg: '#0d0600',
    particle: 'sparkles',
  },
  {
    id: 'graduation',
    name: 'Graduation',
    nameTh: 'ยินดีสำเร็จการศึกษา',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'แสดงความยินดีกับความสำเร็จครั้งยิ่งใหญ่',
    icon: 'school',
    from: '#1D4ED8', to: '#7C3AED',
    bg: '#00050d',
    particle: 'stars',
  },
  {
    id: 'apology',
    name: 'I\'m Sorry',
    nameTh: 'ขอโทษจากใจ',
    category: 'feelings',
    categoryTh: 'ความรู้สึก',
    desc: 'บอกความจริงจากใจ พร้อมขอโทษอย่างจริงจัง',
    icon: 'sentiment_dissatisfied',
    from: '#A78BFA', to: '#818CF8',
    bg: '#04000d',
    particle: 'none',
  },
  {
    id: 'thankyou',
    name: 'Thank You',
    nameTh: 'ขอบคุณมากๆ',
    category: 'feelings',
    categoryTh: 'ความรู้สึก',
    desc: 'สื่อสารความขอบคุณจากก้นบึ้งของหัวใจ',
    icon: 'volunteer_activism',
    from: '#10B981', to: '#059669',
    bg: '#00090a',
    particle: 'sparkles',
  },
  {
    id: 'motivation',
    name: 'You Got This!',
    nameTh: 'สู้ๆ นะ!',
    category: 'motivation',
    categoryTh: 'แรงบันดาลใจ',
    desc: 'ให้กำลังใจในช่วงเวลาที่ยากลำบาก',
    icon: 'rocket_launch',
    from: '#F97316', to: '#EF4444',
    bg: '#0d0500',
    particle: 'stars',
  },
  {
    id: 'goodmorning',
    name: 'Good Morning',
    nameTh: 'อรุณสวัสดิ์',
    category: 'daily',
    categoryTh: 'ชีวิตประจำวัน',
    desc: 'เริ่มต้นวันใหม่ด้วยรอยยิ้มและความรัก',
    icon: 'wb_sunny',
    from: '#FCD34D', to: '#F97316',
    bg: '#0d0700',
    particle: 'glow',
  },
  {
    id: 'missyou',
    name: 'I Miss You',
    nameTh: 'คิดถึงนะ',
    category: 'feelings',
    categoryTh: 'ความรู้สึก',
    desc: 'บอกว่าคิดถึงเขาแค่ไหนในช่วงที่อยู่ห่างกัน',
    icon: 'favorite_border',
    from: '#3B82F6', to: '#6366F1',
    bg: '#00040d',
    particle: 'stars',
  },
  {
    id: 'newyear',
    name: 'Happy New Year',
    nameTh: 'สวัสดีปีใหม่',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'อวยพรปีใหม่ด้วยความปรารถนาดีจากใจ',
    icon: 'auto_awesome',
    from: '#FBBF24', to: '#EF4444',
    bg: '#0d0800',
    particle: 'confetti',
  },
  {
    id: 'christmas',
    name: 'Merry Christmas',
    nameTh: 'คริสต์มาสสุขสันต์',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'ส่งความอบอุ่นและรอยยิ้มในเทศกาลคริสต์มาส',
    icon: 'ac_unit',
    from: '#EF4444', to: '#16A34A',
    bg: '#000d00',
    particle: 'snow',
  },
  {
    id: 'congrats',
    name: 'Congratulations',
    nameTh: 'ยินดีด้วยนะ!',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'ฉลองความสำเร็จและความภาคภูมิใจ',
    icon: 'emoji_events',
    from: '#8B5CF6', to: '#3B82F6',
    bg: '#04000d',
    particle: 'confetti',
  },
  {
    id: 'getwell',
    name: 'Get Well Soon',
    nameTh: 'หายไวๆ นะ',
    category: 'feelings',
    categoryTh: 'ความรู้สึก',
    desc: 'ส่งความเป็นห่วงใยและพลังงานบวกๆ',
    icon: 'health_and_safety',
    from: '#34D399', to: '#60A5FA',
    bg: '#000d08',
    particle: 'sparkles',
  },
  {
    id: 'goodluck',
    name: 'Good Luck',
    nameTh: 'โชคดีนะ!',
    category: 'motivation',
    categoryTh: 'แรงบันดาลใจ',
    desc: 'ส่งโชคดีและพลังใจก่อนวันสำคัญ',
    icon: 'stars',
    from: '#7C3AED', to: '#FBBF24',
    bg: '#04000d',
    particle: 'stars',
  },
  {
    id: 'proposal',
    name: 'Will You Marry Me?',
    nameTh: 'แต่งงานกันนะ',
    category: 'love',
    categoryTh: 'ความรัก',
    desc: 'ช่วงเวลาพิเศษที่สุดในชีวิต บอกเขาจากใจ',
    icon: 'diamond',
    from: '#F43F5E', to: '#FB923C',
    bg: '#0d0000',
    particle: 'hearts',
  },
  {
    id: 'baby',
    name: 'Welcome Baby',
    nameTh: 'ยินดีต้อนรับน้องใหม่',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'ยินดีกับการมาถึงของสมาชิกใหม่ในครอบครัว',
    icon: 'child_care',
    from: '#A5B4FC', to: '#FDA4AF',
    bg: '#04000d',
    particle: 'bubbles',
  },
  {
    id: 'promotion',
    name: 'Congratulations on Your Promotion',
    nameTh: 'ยินดีกับตำแหน่งใหม่',
    category: 'occasion',
    categoryTh: 'โอกาสพิเศษ',
    desc: 'เฉลิมฉลองความก้าวหน้าและความสำเร็จในการงาน',
    icon: 'trending_up',
    from: '#FBBF24', to: '#D97706',
    bg: '#0d0900',
    particle: 'sparkles',
  },
  {
    id: 'travel',
    name: 'Bon Voyage',
    nameTh: 'เดินทางปลอดภัยนะ',
    category: 'daily',
    categoryTh: 'ชีวิตประจำวัน',
    desc: 'ส่งพลังดีๆ และความปลอดภัยสำหรับการเดินทาง',
    icon: 'flight_takeoff',
    from: '#06B6D4', to: '#3B82F6',
    bg: '#00050d',
    particle: 'none',
  },
  {
    id: 'justbecause',
    name: 'Just Because',
    nameTh: 'แค่อยากบอก',
    category: 'daily',
    categoryTh: 'ชีวิตประจำวัน',
    desc: 'บอกความรู้สึกดีๆ โดยไม่ต้องมีเหตุผลพิเศษ',
    icon: 'sentiment_very_satisfied',
    from: '#EC4899', to: '#8B5CF6',
    bg: '#0d0008',
    particle: 'sparkles',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'ทั้งหมด' },
  { id: 'love', label: 'ความรัก' },
  { id: 'birthday', label: 'วันเกิด' },
  { id: 'friendship', label: 'มิตรภาพ' },
  { id: 'occasion', label: 'โอกาสพิเศษ' },
  { id: 'feelings', label: 'ความรู้สึก' },
  { id: 'motivation', label: 'แรงบันดาลใจ' },
  { id: 'daily', label: 'ชีวิตประจำวัน' },
];

export function getTemplateById(id) {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}
