// ==========================================
// 🟡 STANDARD TIER (แพ็กเกจ 20 บาท - 30 Templates)
// ==========================================
export const TEMPLATES_2 = [
  // Group 1: ความรัก & คนพิเศษ
  { id: 'anniversarybox', part: 1, name: 'Anniversary Box', nameTh: 'กล่องของขวัญหมุนได้', category: 'love', categoryTh: 'ความรัก', desc: 'กล่องของขวัญหมุนได้ พอคลิกแล้วกล่องเปิดมีรูปโผล่ออกมา', icon: 'redeem', from: '#D4AF37', to: '#C2185B', bg: '#0d0a00', particle: 'petals', tier: 'standard' },
  { id: 'neonheart', part: 2, name: 'Neon Heart', nameTh: 'หัวใจนีออน', category: 'love', categoryTh: 'ความรัก', desc: 'สไตล์ป้ายไฟนีออนสว่างไสวในเงามืด ไฟกะพริบตามจังหวะ', icon: 'favorite_border', from: '#FF0055', to: '#7700FF', bg: '#050011', particle: 'glow', tier: 'standard' },
  { id: 'lanterns', part: 2, name: 'Night Sky Lanterns', nameTh: 'โคมลอยดวงดาว', category: 'love', categoryTh: 'ความรัก', desc: 'ปล่อยโคมลอยขึ้นฟ้า เลื่อนดูโคมลอยสูงขึ้นได้', icon: 'wb_incandescent', from: '#FFB703', to: '#FB8500', bg: '#020024', particle: 'stars', tier: 'standard' },
  { id: 'redthread', part: 3, name: 'Red Thread', nameTh: 'ด้ายแดงแห่งโชคชะตา', category: 'love', categoryTh: 'ความรัก', desc: 'ด้ายแดงแห่งโชคชะตา โยงจากขอบจอมาผูกกันเป็นรูปหัวใจ', icon: 'gesture', from: '#D90429', to: '#EF233C', bg: '#0a0005', particle: 'none', tier: 'standard' },
  { id: 'starrynight', part: 3, name: 'Starry Night', nameTh: 'ท้องฟ้าจำลอง', category: 'love', categoryTh: 'ความรัก', desc: 'ท้องฟ้าจำลอง มีดาวตกเมื่อเอานิ้วลากผ่านหน้าจอ', icon: 'nights_stay', from: '#4EA8DE', to: '#03045E', bg: '#010014', particle: 'stars', tier: 'standard' },
  { id: 'polaroid', part: 2, name: 'Polaroid Memory', nameTh: 'ความทรงจำโพลารอยด์', category: 'love', categoryTh: 'ความรัก', desc: 'รูปโพลารอยด์หล่นลงมาทีละใบ แล้วพลิกกลับด้านเป็นข้อความ', icon: 'photo_camera', from: '#E0A96D', to: '#DDC3A5', bg: '#121212', particle: 'sparkles', tier: 'standard' },
  { id: 'origami', part: 2, name: 'Origami Swan', nameTh: 'นกพับกระดาษ', category: 'love', categoryTh: 'ความรัก', desc: 'นกกระดาษพับลอยขยับปีกได้ แล้วคลายตัวออกเป็นจดหมาย', icon: 'flight_sm', from: '#8ECAE6', to: '#219EBC', bg: '#101B24', particle: 'none', tier: 'standard' },
  { id: 'cupid', part: 1, name: 'Cupid\'s Arrow', nameTh: 'ศรคิวปิด', category: 'love', categoryTh: 'ความรัก', desc: 'ธนูปักกลางจอ แล้วหน้าจอแตกเป็นกลีบกุหลาบ', icon: 'crisis_alert', from: '#FF758F', to: '#C9184A', bg: '#10000B', particle: 'petals', tier: 'standard' },
  { id: 'lovespell', part: 2, name: 'Love Spell', nameTh: 'เวทมนตร์แห่งรัก', category: 'love', categoryTh: 'ความรัก', desc: 'วงแหวนเวทมนตร์เรืองแสงตรงกลาง ก่อนระเบิดเป็นละอองแสง', icon: 'blur_on', from: '#B100E8', to: '#00E8FC', bg: '#08001F', particle: 'glow', tier: 'standard' },
  { id: 'rainywindow', part: 3, name: 'Rainy Window', nameTh: 'หน้าต่างวันฝนตก', category: 'love', categoryTh: 'ความรัก', desc: 'หยดน้ำฝนเกาะหน้าต่างกระจก เอานิ้วเช็ดฝ้ากระจกเพื่ออ่านข้อความ', icon: 'water_drop', from: '#48CAE4', to: '#0077B6', bg: '#0B132B', particle: 'none', tier: 'standard' },

  // Group 2: โอกาสพิเศษ & เพื่อน
  { id: 'graduationscroll', part: 2, name: 'Graduation Scroll', nameTh: 'ม้วนกระดาษปริญญา', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'ม้วนกระดาษปริญญาปลดเชือกแล้วกางม้วนออกเป็นข้อความ', icon: 'history_edu', from: '#1D4ED8', to: '#7C3AED', bg: '#00050d', particle: 'stars', tier: 'standard' },
  { id: 'cheers', part: 1, name: 'Cheers!', nameTh: 'ชนแก้วฉลอง', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'แก้วเครื่องดื่มชนกันจ๊อกกิ้ง แล้วฟองฟู่ขึ้นมาบังจอ', icon: 'local_cafe', from: '#F9A826', to: '#F67280', bg: '#0d0d0d', particle: 'bubbles', tier: 'standard' },
  { id: 'cyberpunk', part: 1, name: 'Cyberpunk Hacker', nameTh: 'รหัสแฮกเกอร์', category: 'friendship', categoryTh: 'มิตรภาพ', desc: 'โค้ดสีเขียวร่วงหล่น (Matrix) แล้วค่อยๆ ถอดรหัสเป็นข้อความ', icon: 'terminal', from: '#00FF41', to: '#008F11', bg: '#000000', particle: 'none', tier: 'standard' },
  { id: 'arcade', part: 1, name: 'Retro 80s Arcade', nameTh: 'เกมตู้ 80s', category: 'friendship', categoryTh: 'มิตรภาพ', desc: 'หน้าจอเกมตู้สไตล์ 80s ต้องกดปุ่ม Start เพื่อปล่อยลำแสง', icon: 'sports_esports', from: '#FF007F', to: '#7900FF', bg: '#0A0A0A', particle: 'sparkles', tier: 'standard' },
  { id: 'vinyl', part: 3, name: 'Vinyl Player', nameTh: 'เครื่องเล่นแผ่นเสียง', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'เครื่องเล่นแผ่นเสียงหมุน มีเข็มวางลงและข้อความวิ่งรอบๆ', icon: 'album', from: '#F4A261', to: '#E76F51', bg: '#1A1A1A', particle: 'glow', tier: 'standard' },
  { id: 'apologytear', part: 1, name: 'Apology Tear', nameTh: 'หยดน้ำตาขอโทษ', category: 'feelings', categoryTh: 'ความรู้สึก', desc: 'น้ำตาหยดลงน้ำ เกิดระลอกคลื่นขยับตัวหนังสือไปมา', icon: 'water', from: '#8ECAE6', to: '#023047', bg: '#050F14', particle: 'none', tier: 'standard' },
  { id: 'goldenticket', part: 2, name: 'Golden Ticket', nameTh: 'ตั๋วทองคำ', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'ฟอยล์สะท้อนแสงแวววาวเวลาหมุนจอ (รับโชค)', icon: 'local_activity', from: '#FFD700', to: '#DAA520', bg: '#1F1A05', particle: 'sparkles', tier: 'standard' },
  { id: 'fortunecookie', part: 1, name: 'Fortune Cookie', nameTh: 'คุกกี้เสี่ยงทาย', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'คุกกี้เสี่ยงทาย ใช้นิ้วปาดเพื่อบิออกเป็นสองซีก', icon: 'bakery_dining', from: '#F6AA1C', to: '#BC3908', bg: '#1A120B', particle: 'none', tier: 'standard' },
  { id: 'scratchcard', part: 3, name: 'Scratch Card', nameTh: 'การ์ดขูดลุ้นโชค', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'การ์ดขูดลุ้นโชค ต้องเอานิ้วถูหน้าจอเพื่อขูดเนื้อสีเงินออก', icon: 'straighten', from: '#A8DADC', to: '#457B9D', bg: '#1D3557', particle: 'sparkles', tier: 'standard' },
  { id: 'magicpostcard', part: 2, name: 'Magic Postcard', nameTh: 'โปสการ์ดทะลุมิติ', category: 'friendship', categoryTh: 'มิตรภาพ', desc: 'โปสการ์ดทะลุจอ มีแสตมป์เรืองแสงบินได้', icon: 'mark_as_unread', from: '#E5989B', to: '#6D6875', bg: '#19151A', particle: 'stars', tier: 'standard' },

  // Group 3: ชีวิตประจำวัน & สไตล์เก๋ไก๋
  { id: 'morningcoffee', name: 'Morning Coffee', nameTh: 'กาแฟยามเช้า', category: 'daily', categoryTh: 'ชีวิตประจำวัน', desc: 'ควันแก้วกาแฟลอยขึ้นมา จัดเรียงตัวเป็นคำทักทายตอนเช้า', icon: 'coffee', from: '#D4A373', to: '#FAEDCD', bg: '#1A1412', particle: 'none', tier: 'standard' },
  { id: 'goodnightmoon', name: 'Goodnight Moon', nameTh: 'ราตรีสวัสดิ์', category: 'daily', categoryTh: 'ชีวิตประจำวัน', desc: 'แสงจันทร์ส่องผ่านหน้าต่าง มู่ลี่ค่อยๆ เปิดขึ้นพร้อมข้อความ', icon: 'dark_mode', from: '#BDE0FE', to: '#A2D2FF', bg: '#03045E', particle: 'stars', tier: 'standard' },
  { id: 'getwellcapsule', name: 'Get Well Capsule', nameTh: 'แคปซูลฟื้นฟู', category: 'feelings', categoryTh: 'ความรู้สึก', desc: 'เม็ดยาหล่นตกลงมาแตกตัวเป็นพลังงานบวกรักษาคนป่วย', icon: 'medication', from: '#06D6A0', to: '#118AB2', bg: '#071A21', particle: 'glow', tier: 'standard' },
  { id: 'motivationrocket', name: 'Motivation Rocket', nameTh: 'จรวดให้กำลังใจ', category: 'motivation', categoryTh: 'แรงบันดาลใจ', desc: 'จรวดจุดระเบิดบินทะลุชั้นบรรยากาศสู่ดวงดาว', icon: 'rocket_launch', from: '#EF476F', to: '#FFD166', bg: '#1A0E19', particle: 'stars', tier: 'standard' },
  { id: 'typewriter', part: 3, name: 'Old-school Typewriter', nameTh: 'เครื่องพิมพ์ดีด', category: 'daily', categoryTh: 'ชีวิตประจำวัน', desc: 'พิมพ์ดีดโบราณ พิมพ์ข้อความทีละตัวอักษรกระดาษเลื่อนขึ้น', icon: 'keyboard', from: '#264653', to: '#2A9D8F', bg: '#0B1519', particle: 'none', tier: 'standard' },
  { id: 'travelticket', name: 'Travel Ticket', nameTh: 'ตั๋วเดินทาง', category: 'daily', categoryTh: 'ชีวิตประจำวัน', desc: 'ตั๋วเครื่องบินเก๋ๆ บาร์โค้ดสแกนแสงเลเซอร์แล้วตั๋วทำงาน', icon: 'flight', from: '#F4A261', to: '#E76F51', bg: '#140D0B', particle: 'none', tier: 'standard' },
  { id: 'zengarden', name: 'Zen Garden', nameTh: 'สวนเซน', category: 'daily', categoryTh: 'ชีวิตประจำวัน', desc: 'คราดทรายสไตล์ญี่ปุ่น วาดลวดลายทรายค่อยๆ ปรากฏเป็นคำพูด', icon: 'park', from: '#81B29A', to: '#3D405B', bg: '#171A11', particle: 'none', tier: 'standard' },
  { id: 'newyearfireworks', name: 'New Year Fireworks', nameTh: 'พลุฉลองปีใหม่', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'พลุฉลอง จิ้มที่จอเพื่อยิงพลุสีต่างๆ ด้วยตัวเองได้', icon: 'celebration', from: '#F94144', to: '#F9C74F', bg: '#110505', particle: 'confetti', tier: 'standard' },
  { id: 'snowglobe', part: 3, name: 'Christmas Snowglobe', nameTh: 'ลูกแก้วหิมะ', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'ลูกแก้วหิมะ เขย่ามือถือเพื่อให้หิมะตกหมุนวน', icon: 'ac_unit', from: '#90BE6D', to: '#43AA8B', bg: '#0B1410', particle: 'snow', tier: 'standard' },
  { id: 'babyblocks', name: 'Baby Blocks', nameTh: 'บล็อกของเล่น', category: 'occasion', categoryTh: 'โอกาสพิเศษ', desc: 'บล็อกไม้ตกลงมาเรียงตัวเป็นชื่อต้อนรับหลาน/ลูก', icon: 'toys', from: '#F8961E', to: '#F9C74F', bg: '#19140B', particle: 'none', tier: 'standard' }
];
