// ==========================================
// 🔴 PREMIUM TIER (แพ็กเกจ 120 บาท - 100 Templates)
// ==========================================
export const TEMPLATES_3 = [
  // Category 1: 🌌 อวกาศและไซไฟอลังการ (Space & Sci-Fi)
  { id: 'warpspeed', part: 3, name: 'Warp Speed Proposal', nameTh: 'วาร์ปขอแต่งงาน', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'ยานเร่งความเร็ววาร์ป ทะลุเข้าทุ่งดวงดาว 3D', icon: 'speed', from: '#020024', to: '#090979', bg: '#000000', particle: 'stars', tier: 'premium' },
  { id: 'blackhole', part: 1, name: 'Blackhole Journey', nameTh: 'ปริศนาหลุมดำ', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'ถูกดูดตกลงหลุมดำ 3D แล้วไปโผล่อีกมิติ', icon: 'trip_origin', from: '#000000', to: '#430000', bg: '#000000', particle: 'glow', tier: 'premium' },
  { id: 'marslanding', part: 2, name: 'Mars Landing', nameTh: 'ลงจอดดาวอังคาร', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'รถโรเวอร์ลงจอด ทิ้งรอยล้อเป็นข้อความบนทราย', icon: 'public', from: '#B7410E', to: '#E56B3C', bg: '#1A0800', particle: 'dust', tier: 'premium' },
  { id: 'hologram', part: 2, name: 'Hologram Projector', nameTh: 'โดรนโฮโลแกรม', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'โดรนบินมาเพื่อฉายเลเซอร์โฮโลแกรมลอย 3 มิติกลางอากาศ', icon: 'memory', from: '#00FFF5', to: '#0088FF', bg: '#001A22', particle: 'none', tier: 'premium' },
  { id: 'constellation', part: 1, name: 'Constellation', nameTh: 'กลุ่มดาวบนฟ้า', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'ลากเส้นเชื่อมกลุ่มดาวบนฟ้าให้ออกมาเป็นข้อความและรูปภาพ', icon: 'auto_awesome', from: '#0F2027', to: '#203A43', bg: '#050D11', particle: 'stars', tier: 'premium' },
  { id: 'alienabduction', part: 1, name: 'Alien Abduction', nameTh: 'ยูเอฟโอลักพาตัว', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'UFO บินมาดูดตัวข้อความขึ้นไปบนยาน (แนวตลก)', icon: 'smart_toy', from: '#1A2A6C', to: '#B21F1F', bg: '#0A0514', particle: 'glow', tier: 'premium' },
  { id: 'aicore', part: 1, name: 'AI Core', nameTh: 'แกนพลังงาน AI', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'แกนพลังกะพริบ แปลภาษาโรบอทเป็นข้อความคำอวยพรไซไฟ', icon: 'settings_input_component', from: '#000000', to: '#00FF00', bg: '#000F05', particle: 'none', tier: 'premium' },
  { id: 'meteorshower', part: 2, name: 'Meteor Shower', nameTh: 'ฝนดาวตก', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'ดาวตกพุ่งชนกลายเป็นลูกไฟและเศษซากตัวอักษร', icon: 'local_fire_department', from: '#4B1248', to: '#F0C27B', bg: '#120210', particle: 'sparkles', tier: 'premium' },
  { id: 'galaxyportal', part: 1, name: 'Galaxy Portal', nameTh: 'ประตูมิติอวกาศ', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'ประตูกาลเวลาเปิดออกหมุนวน เผยข้อความจากอนาคต', icon: 'camera', from: '#2C3E50', to: '#3498DB', bg: '#080C0F', particle: 'glow', tier: 'premium' },
  { id: 'spacestation', part: 3, name: 'Space Station Window', nameTh: 'วิวสถานีอวกาศ', category: 'sci-fi', categoryTh: 'ไซไฟอวกาศ', desc: 'มองผ่านหน้าต่างยานอวกาศ ข้อความพาดผ่านโลกหมุน', icon: 'satellite', from: '#000046', to: '#1CB5E0', bg: '#000018', particle: 'none', tier: 'premium' },

  // Category 2: 🏰 แฟนตาซีและเวทย์มนต์ (Fantasy & Magic)
  { id: 'dragon', part: 1, name: 'Dragon\'s Treasure', nameTh: 'สมบัติมังกร', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'มังกรบินขนาบจอ พ่นไฟละลายทองเพื่อแสดงข้อความ', icon: 'local_fire_department', from: '#1A0000', to: '#5C0000', bg: '#0A0000', particle: 'sparkles', tier: 'premium' },
  { id: 'wizardbook', part: 3, name: 'Wizard\'s Book', nameTh: 'คัมภีร์เวทมนตร์', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'หนังสือเวทมนตร์ลอยปลิวพลิกหน้า แสงเวทพุ่งร่ายมนต์', icon: 'menu_book', from: '#2A0845', to: '#6441A5', bg: '#0B0510', particle: 'glow', tier: 'premium' },
  { id: 'magicwand', part: 2, name: 'Magic Wand', nameTh: 'ร่ายไม้กายสิทธิ์', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'ไม้กายสิทธิ์ร่ายเวทตวัดสัญลักษณ์เปิดผนึกข้อความ', icon: 'auto_fix_high', from: '#00223E', to: '#1D976C', bg: '#00111A', particle: 'stars', tier: 'premium' },
  { id: 'magicpotion', part: 2, name: 'Magic Potion', nameTh: 'ปรุงยาชุบชีวิต', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'หย่อนส่วนผสมลงหม้อปรุงยาให้เดือดปุดๆ ก่อนระเบิดเป็นข้อความ', icon: 'science', from: '#8B5CF6', to: '#10B981', bg: '#051A10', particle: 'bubbles', tier: 'premium' },
  { id: 'magicmirror', part: 2, name: 'Magic Mirror', nameTh: 'กระจกวิเศษ', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'กระจกโบราณมีหมอกควัน พอกดแล้วเผยการปรากฏตัวสะท้อนใจ', icon: 'crop_portrait', from: '#475569', to: '#E2E8F0', bg: '#01000A', particle: 'none', tier: 'premium' },
  { id: 'crystalball', part: 1, name: 'Crystal Ball', nameTh: 'ลูกแก้วหยั่งรู้', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'ลูกแก้วพยากรณ์มีพลาสมาหมุนวน เผยโชคชะตาและคำทำนาย', icon: 'radio_button_checked', from: '#8A2BE2', to: '#00FFFF', bg: '#0A0014', particle: 'glow', tier: 'premium' },
  { id: 'tarot', part: 3, name: 'Tarot Card', nameTh: 'ไพ่ทาโรต์ทำนายรัก', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'ไพ่ทาโรต์คว่ำหน้าอยู่ พอกดพลิกไพ่ 3 มิติจะเผยคำทำนายโชคชะตา', icon: 'style', from: '#2A1B3D', to: '#D4AF37', bg: '#0B0515', particle: 'none', tier: 'premium' },
  { id: 'glowingcave', part: 1, name: 'Glowing Cave', nameTh: 'ถ้ำผลึกเรืองแสง', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'ถ้ำมืดมิดที่มีคริสตัล พอกดคริสตัลจะสว่างจ้าส่องสว่างทั้งถ้ำ', icon: 'landscape', from: '#00FFFF', to: '#0055FF', bg: '#02050A', particle: 'glow', tier: 'premium' },
  { id: 'ancientseal', part: 1, name: 'Ancient Seal', nameTh: 'ผนึกเวทมนตร์โบราณ', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'วงเวทอักขระหมุนวนปกป้องข้อความ พอกดทำลายผนึกจะระเบิดออก', icon: 'lock', from: '#FF3300', to: '#FFD700', bg: '#0A0100', particle: 'none', tier: 'premium' },
  { id: 'fairyforest', part: 1, name: 'Fairy Forest', nameTh: 'ป่าแฟรี่เรืองแสง', category: 'fantasy', categoryTh: 'แฟนตาซีเวทมนตร์', desc: 'ป่าต้องมนต์หิ่งห้อย พอกดดอกไม้วิเศษจะเบ่งบานเปล่งแสงอลังการ', icon: 'forest', from: '#A78BFA', to: '#5B21B6', bg: '#011A11', particle: 'stars', tier: 'premium' },

  // Category 3: 🕹️ มินิเกมอินเทอร์แอคทีฟ (Interactive Minigames)
  { id: '8bitblock', part: 1, name: '8-Bit Block Punch', nameTh: 'ทุบกล่องบิตคริสตัล', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'กล่องคำถามมาริโอ้ เอานิ้วจิ้มทุบรัวๆ ให้ครบ 5 ครั้งเพื่อคว้าข้อความ', icon: 'videogame_asset', from: '#FFCE00', to: '#E52521', bg: '#5C94FC', particle: 'none', tier: 'premium' },
  { id: 'safecracker', part: 3, name: 'Safe Cracker', nameTh: 'หมุนตู้เซฟรหัส', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ตู้เซฟเหล็กนิรภัย ลากนิ้วหมุนรหัสเกียร์ให้เข้าที่เพื่อปลดล็อกเซฟ', icon: 'vpn_key', from: '#48BB78', to: '#2D3748', bg: '#1A202C', particle: 'none', tier: 'premium' },
  { id: 'clawmachine', part: 1, name: 'Claw Machine', nameTh: 'ตู้คีบตุ๊กตาแคปซูล', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'กดปุ่มเลื่อนมือจับไปตรงแคปซูลไข่เพื่อหยิบข้อความเซอร์ไพรส์', icon: 'precision_manufacturing', from: '#F6AD55', to: '#C53030', bg: '#2C7A7B', particle: 'none', tier: 'premium' },
  { id: 'popballoon', part: 3, name: 'Pop the Balloon', nameTh: 'จิ้มลูกโป่งแตก', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ลูกโป่งหลากสีลอยขึ้นฟ้า จิ้มเป้าหมายให้แตกตรงสีเพื่อเปิดตัวข้อความ', icon: 'celebration', from: '#4299E1', to: '#ED8936', bg: '#2B6CB0', particle: 'none', tier: 'premium' },
  { id: 'gachapon', part: 1, name: 'Gachapon Machine', nameTh: 'สุ่มตู้กาชาปอง', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ไขตู้กาชาปองเครื่องหมุน แล้วแคปซูลรางวัลจะตกลงมาให้กดเปิด', icon: 'catching_pokemon', from: '#FF9F1C', to: '#E71D36', bg: '#FF6B6B', particle: 'none', tier: 'premium' },
  { id: 'memorycard', part: 2, name: 'Memory Match', nameTh: 'ลุ้นจับคู่ไพ่', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'เกมจับคู่รูปภาพเหมือนกัน พลิกไพ่ให้ตรงคู่ถึงจะเปิดอ่านคำอวยพรได้', icon: 'style', from: '#38B2AC', to: '#D53F8C', bg: '#4FD1C5', particle: 'none', tier: 'premium' },
  { id: 'slotmachine', part: 3, name: 'Slot Machine', nameTh: 'สล็อตแจ็คพอต', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ดึงคันโยกตู้สล็อตแมชชีน หมุนรอให้สัญลักษณ์ตรงกันเพื่อรับรางวัลแจ็คพอต', icon: 'casino', from: '#ED8936', to: '#C05621', bg: '#2D3748', particle: 'none', tier: 'premium' },
  { id: 'spinwheel', part: 3, name: 'Spin the Wheel', nameTh: 'วงล้อเสี่ยงโชค', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'กดหมุนวงล้อเสี่ยงโชคสีสันสดใสแบบรายการทีวี เพื่อลุ้นรับข้อความ', icon: 'radio_button_checked', from: '#9F7AEA', to: '#E53E3E', bg: '#6B46C1', particle: 'none', tier: 'premium' },
  { id: 'whackamole', part: 3, name: 'Whack-a-Mole', nameTh: 'ตีตัวตุ่น', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ตัวตุ่นโผล่มาจากหลุม จิ้มตีตัวตุ่นให้ได้คะแนนเป้าหมายเพื่อรับสาส์น', icon: 'pest_control_rodent', from: '#8BC34A', to: '#33691E', bg: '#7CB342', particle: 'none', tier: 'premium' },
  { id: 'scratchcard', part: 3, name: 'Scratch Card Extreme', nameTh: 'ขูดบัตรลุ้นโชค', category: 'minigame', categoryTh: 'มินิเกมอินเทอร์แอคทีฟ', desc: 'ใช้นิ้วถูหน้าจอเพื่อขูดเนื้อฟอยล์สีเงินออก เปิดเผยข้อความเซอร์ไพรส์ที่ซ่อนอยู่', icon: 'credit_card', from: '#FFD700', to: '#A0AEC0', bg: '#2D3748', particle: 'none', tier: 'premium' },

  // Category 4: 🍿 ประสบการณ์ภาพยนตร์ (Movie Experiences)
  { id: 'classicfilm', part: 1, name: 'Vintage Cinema', nameTh: 'ฟิล์มภาพยนตร์ม้วนเก่า', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'นับถอยหลังเปิดตัวฟิล์มเก่าคลาสสิกขาวดำ ก่อนฉายข้อความสุดพิเศษ', icon: 'movie', from: '#2D3748', to: '#000000', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'vipticket', part: 3, name: 'Golden Ticket', nameTh: 'ตั๋ววีไอพีสีทอง', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'ตั๋วชมภาพยนตร์ 3D ลอยมากลางจอ พอกดฉีกตั๋วจะเผยหนังรอบปฐมทัศน์', icon: 'local_activity', from: '#ECC94B', to: '#2D3748', bg: '#1A202C', particle: 'none', tier: 'premium' },
  { id: 'spacecrawl', part: 3, name: 'Space Crawl', nameTh: 'มหากาพย์อวกาศ', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'ข้อความสีเหลืองเลื่อนขึ้นช้าๆ ทะยานสู่หมู่ดาวแบบมหากาพย์หนังดัง', icon: 'rocket_launch', from: '#FFE81F', to: '#000000', bg: '#000000', particle: 'stars', tier: 'premium' },
  { id: 'kdrama', part: 2, name: 'K-Drama Subtitles', nameTh: 'ซับไตเติลซีรีส์เกาหลี', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'ซีนหิมะตกสุดตราตรึง พร้อมข้อความขึ้นทีละบรรทัดแบบซับไตเติลซีรีส์', icon: 'subtitles', from: '#E2E8F0', to: '#4A5568', bg: '#000000', particle: 'snow', tier: 'premium' },
  { id: 'actionfilm', part: 1, name: 'Action Blockbuster', nameTh: 'ฉากแอคชั่นระเบิดภูเขา', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'กดปุ่มจุดชนวน ให้ฉากหลังระเบิดตู้ม! ควันตลบก่อนข้อความจะกระแทกจอ', icon: 'explosion', from: '#E53E3E', to: '#050505', bg: '#050505', particle: 'none', tier: 'premium' },
  { id: 'awardenvelope', part: 1, name: 'Oscar Award', nameTh: 'ซองประกาศผลรางวัล', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'จำลองงานประกาศออสการ์ เปิดซองจดหมายสีทองท่ามกลางสายฝนกระดาษ', icon: 'stars', from: '#FCD34D', to: '#D97706', bg: '#0f172a', particle: 'confetti', tier: 'premium' },
  { id: 'matrix', part: 2, name: 'Cyber Hacker', nameTh: 'แฮกเกอร์ไซไฟ (Matrix)', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'ตัวอักษรสีเขียวโค้ดลับร่วงหล่น พร้อมพิมพ์ข้อความทีละตัวแบบหน้าจอแฮกเกอร์', icon: 'terminal', from: '#22C55E', to: '#064E3B', bg: '#000000', particle: 'matrix', tier: 'premium' },
  { id: 'clapperboard', part: 1, name: 'Director Slate', nameTh: 'สเลทผู้กำกับภาพยนตร์', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'สเลทสีดำกดสับกล้องดังแป๊ก! สั่งเดินกล้องเพื่อเปิดข้อความซีนของคุณ', icon: 'movie_edit', from: '#FACC15', to: '#18181B', bg: '#3F3F46', particle: 'none', tier: 'premium' },
  { id: 'filmcamera', part: 1, name: 'Vintage Polaroid', nameTh: 'ถ่ายรูปโพลารอยด์วินเทจ', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'กดปุ่มชัตเตอร์มีแสงแฟลชวาบ แล้วรูปจะค่อยๆ ผลิตล้างภาพข้อความออกมา', icon: 'camera_alt', from: '#3B82F6', to: '#1E293B', bg: '#F1F5F9', particle: 'none', tier: 'premium' },
  { id: 'horrorfilm', part: 2, name: 'Horror Flashlight', nameTh: 'สยองขวัญไฟฉาย', category: 'movie', categoryTh: 'ประสบการณ์ภาพยนตร์', desc: 'ต้องลากไฟฉายสำรวจความมืด พอเจอเป้าหมายจะมีป๊อบอัพไฟแดงแฟลชใส่!', icon: 'flashlight_on', from: '#991B1B', to: '#000000', bg: '#000000', particle: 'none', tier: 'premium' },

  // Category 5: 🖼️ สามมิติสมจริง (Photorealistic)
  { id: 'musicbox', part: 2, name: 'Wind-up Music Box', nameTh: 'กล่องดนตรีไขลาน', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'กล่องดนตรีไม้ 3 มิติ กดไขลานเพื่อให้กล่องเปิดออกเผยข้อความและแสงระยิบระยับ', icon: 'music_note', from: '#D97706', to: '#7C2D12', bg: '#1a0f05', particle: 'none', tier: 'premium' },
  { id: 'snowglobe_winter', part: 3, name: 'Winter Snow Globe', nameTh: 'ลูกแก้วหิมะฤดูหนาว', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'เขย่าลูกแก้วหิมะ 3D เพื่อให้หิมะตกโปรยปรายลงมา พร้อมเผยข้อความปริศนาด้านหลัง', icon: 'ac_unit', from: '#7DD3FC', to: '#0284C7', bg: '#E0F2FE', particle: 'none', tier: 'free' },
  { id: 'vintagemail', part: 3, name: 'Vintage Mailbox', nameTh: 'ตู้จดหมายคลาสสิก', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'ตู้จดหมายอเมริกันริมทาง เปิดฝาตู้แล้วมีจดหมายซองกระดาษพุ่งออกมาเปิดอ่าน', icon: 'mark_email_unread', from: '#E11D48', to: '#9CA3AF', bg: '#F3F4F6', particle: 'none', tier: 'premium' },
  { id: 'messagebottle', part: 2, name: 'Message in a Bottle', nameTh: 'จดหมายในขวดแก้ว', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'ขวดแก้วลอยเกยตื้นบนหาดทราย เปิดจุกก๊อกเพื่อดึงม้วนกระดาษจดหมายออกมา', icon: 'water', from: '#FDE047', to: '#38BDF8', bg: '#BAE6FD', particle: 'none', tier: 'premium' },
  { id: 'compass', part: 1, name: 'Golden Compass', nameTh: 'เข็มทิศแสงดาว', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'เข็มทิศทองเหลือง 3D ดีไซน์หรูหรา เปิดฝาออกเพื่อดูข้อความที่ซ่อนอยู่ตรงหน้าปัด', icon: 'explore', from: '#F59E0B', to: '#1C1917', bg: '#44403C', particle: 'none', tier: 'premium' },
  { id: 'woodenchest', part: 3, name: 'Pirate Treasure Chest', nameTh: 'หีบสมบัติโจรสลัด', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'สำรวจถ้ำมืดมิดและเปิดล็อกหีบสมบัติ 3D เพื่อรับพรคำอวยพรพร้อมเหรียญทองกระเด็น', icon: 'lock', from: '#FACC15', to: '#451A03', bg: '#1c1917', particle: 'none', tier: 'premium' },
  { id: 'antiquebook', part: 1, name: 'Antique Magic Book', nameTh: 'สมุดตำราเวทมนตร์', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'สมุดหนังปกแข็ง 3D พลิกเปิดหน้ากระดาษเก่าๆ เพื่อปรากฏข้อความจากน้ำหมึกเวทมนตร์', icon: 'import_contacts', from: '#78350F', to: '#1c1917', bg: '#292524', particle: 'none', tier: 'premium' },
  { id: 'typewriter_classic', part: 3, name: 'Classic Typewriter', nameTh: 'เครื่องพิมพ์ดีดคลาสสิก', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'เครื่องพิมพ์ดีดโบราณ พิมพ์ข้อความทีละตัวอักษรลงบนกระดาษพร้อมเสียงสมจริง', icon: 'keyboard', from: '#52525B', to: '#18181B', bg: '#27272A', particle: 'none', tier: 'premium' },
  { id: 'skylantern', part: 3, name: 'Floating Sky Lantern', nameTh: 'โคมลอยสวรรค์', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'จุดไฟในโคม 3D แล้วปล่อยให้ลอยขึ้นสู่ท้องฟ้าที่เต็มไปด้วยดวงดาว พร้อมข้อความของคุณ', icon: 'festival', from: '#FDE047', to: '#1E3A8A', bg: '#0F172A', particle: 'none', tier: 'premium' },
  { id: 'vinylrecord', part: 3, name: 'Vintage Turntable', nameTh: 'เครื่องเล่นแผ่นเสียง', category: 'photoreal', categoryTh: 'สามมิติสมจริง', desc: 'เครื่องเล่นแผ่นเสียง 3D เลื่อนหัวเข็มลงเพื่อเล่นเพลงบรรเลงพร้อมข้อความแห่งความทรงจำ', icon: 'album', from: '#9F1239', to: '#4C0519', bg: '#FFF7ED', particle: 'none', tier: 'premium' },

  // Category 6: 🌋 พลังธรรมชาติอลังการ (Nature/Elements)
  { id: 'volcano', part: 3, name: 'Volcanic Eruption', nameTh: 'ภูเขาไฟระเบิด', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'แตะที่ปากปล่องภูเขาไฟเพื่อสร้างระเบิดลาวาพุ่งกระจาย พร้อมข้อความโผล่ขึ้นมาจากความร้อน', icon: 'landscape', from: '#7F1D1D', to: '#050014', bg: '#450a0a', particle: 'none', tier: 'premium' },
  { id: 'aurora', part: 1, name: 'Northern Lights', nameTh: 'แสงเหนือออโรร่า', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'ปัดท้องฟ้าเพื่อเรียกแสงเหนือสีเขียวอมม่วงพลิ้วไหว เผยข้อความใต้แสงดาวตก', icon: 'wb_twilight', from: '#10B981', to: '#020617', bg: '#020617', particle: 'none', tier: 'premium' },
  { id: 'oceanpearl', part: 2, name: 'Deep Ocean Pearl', nameTh: 'ไข่มุกใต้สมุทร', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'ดำดิ่งใต้น้ำลึก เปิดเปลือกหอย 3D เพื่อรับหอยมุกเรืองแสงที่ปล่อยข้อความออกมา', icon: 'scuba_diving', from: '#0284C7', to: '#082F49', bg: '#020617', particle: 'none', tier: 'premium' },
  { id: 'cherryblossom', part: 1, name: 'Cherry Blossom Wind', nameTh: 'สายลมซากุระ', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'เขย่าต้นซากุระเพื่อสร้างพายุกลีบดอกไม้ปลิวไสว ก่อนที่ฉากหลังฟูจิจะเผยข้อความสุขสันต์', icon: 'filter_vintage', from: '#F472B6', to: '#831843', bg: '#FDF2F8', particle: 'none', tier: 'premium' },
  { id: 'solareclipse', part: 3, name: 'Solar Eclipse', nameTh: 'สุริยุปราคาเต็มดวง', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'จับจันทร์เลื่อนมาบังพระอาทิตย์ให้มิด เกิดแสงคอโรน่าเปล่งประกายพร้อมข้อความลึกลับ', icon: 'dark_mode', from: '#000000', to: '#FACC15', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'meteorite', part: 2, name: 'Meteor Strike', nameTh: 'อุกกาบาตดาวตก', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'แตะเพื่อเรียกอุกกาบาตลูกใหญ่พุ่งชนพื้นโลก เกิดแสงวาบและข้อความอิมแพคโผล่จากหลุม', icon: 'local_fire_department', from: '#EA580C', to: '#0F172A', bg: '#1E293B', particle: 'none', tier: 'premium' },
  { id: 'thunderstorm', part: 3, name: 'Lightning Thunder', nameTh: 'พายุสายฟ้าผ่า', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'คลิกในขอบเขตพายุฝนเพื่อฟาดสายฟ้า 2 จังหวะ แล้วเผาไหม้หน้าจอเป็นข้อความสุดเดือด', icon: 'bolt', from: '#38BDF8', to: '#0F172A', bg: '#1E293B', particle: 'none', tier: 'premium' },
  { id: 'rainbow', part: 3, name: 'After Rain Rainbow', nameTh: 'รุ้งกินน้ำหลังฝน', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'กดปัดเป่าเมฆฝนให้ท้องฟ้าเปิด พระอาทิตย์ส่องแสงพร้อมรุ้งกินน้ำโค้งพาดผ่านข้อความ', icon: 'rainbow', from: '#8B5CF6', to: '#3B82F6', bg: '#E0F2FE', particle: 'none', tier: 'premium' },
  { id: 'fireflies', part: 1, name: 'Magic Fireflies', nameTh: 'หิ่งห้อยป่าเวทมนตร์', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'เรียกฝูงหิ่งห้อยหลายร้อยตัวในป่ามืดให้บินมารวมตัวกันส่องสว่างเป็นตัวอักษร', icon: 'pest_control', from: '#A3E635', to: '#064E3B', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'tornado', part: 3, name: 'Twister Tornado', nameTh: 'พายุทอร์นาโด', category: 'nature', categoryTh: 'พลังธรรมชาติอลังการ', desc: 'แตะที่พายุเกลียวงวงช้างขนาดใหญ่ให้มันสลายตัวและพัดพาข้อความอันทรงพลังมาให้', icon: 'cyclone', from: '#A1A1AA', to: '#27272A', bg: '#27272A', particle: 'none', tier: 'premium' },

  // Category 7: 🗽 แลนด์มาร์คสำคัญ (Landmark)
  { id: 'paristower', part: 2, name: 'Eiffel Tower Paris', nameTh: 'หอไอเฟล ปารีส', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'สับสวิตช์เปิดไฟหอไอเฟลยามค่ำคืน พร้อมพลุไฟเฉลิมฉลองและข้อความสุดโรแมนติก', icon: 'eiffel_tower', from: '#1E1B4B', to: '#FACC15', bg: '#020617', particle: 'none', tier: 'premium' },
  { id: 'hieroglyph', part: 2, name: 'Egyptian Pyramid', nameTh: 'พีระมิดอียิปต์', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'ปลุกพีระมิดกลางทะเลทรายให้ยอดแหลมลอยขึ้น เผยดวงตาฮอรัสและศิลาจารึกข้อความ', icon: 'landscape', from: '#D97706', to: '#78350F', bg: '#FCD34D', particle: 'none', tier: 'premium' },
  { id: 'libertytorch', part: 2, name: 'Liberty Torch', nameTh: 'คบเพลิงเสรีภาพ', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'จุดคบเพลิงเทพีเสรีภาพให้สว่างไสว ฝ่าหมอกควันเพื่อประกาศความรู้สึกของคุณ', icon: 'front_hand', from: '#BAE6FD', to: '#EF4444', bg: '#BAE6FD', particle: 'none', tier: 'premium' },
  { id: 'colosseum', part: 1, name: 'Colosseum Gates', nameTh: 'โคลอสเซียม โรม', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'เปิดประตูเหล็กกลาดิเอเตอร์ เดินเข้าสู่ลานประลองพร้อมอัญมณีข้อความศิลาโรมัน', icon: 'account_balance', from: '#FCD34D', to: '#78350F', bg: '#FDBA74', particle: 'none', tier: 'premium' },
  { id: 'tajmahal', part: 3, name: 'Taj Mahal Love', nameTh: 'ทัชมาฮาล รักนิรันดร์', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'เปิดไฟสว่างให้ทัชมาฮาลใต้แสงจันทร์ พร้อมฝนกลีบกุหลาบและข้อความรักอมตะ', icon: 'mosque', from: '#312E81', to: '#FDA4AF', bg: '#1E1B4B', particle: 'none', tier: 'premium' },
  { id: 'greatwall', part: 2, name: 'Great Wall Scroll', nameTh: 'กำแพงเมืองจีน', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'อัญเชิญมังกรทองบินข้ามกำแพงเมืองจีน พร้อมคัมภีร์ม้วนที่ค่อยๆ กางออกเผยข้อความมงคล', icon: 'fort', from: '#FACC15', to: '#78350F', bg: '#B45309', particle: 'none', tier: 'premium' },
  { id: 'stonehenge', part: 3, name: 'Druid Stonehenge', nameTh: 'สโตนเฮนจ์ เวทมนตร์', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'สัมผัสเสาหินเพื่อปลุกพลังอักษรรูนเรืองแสง และยิงลำแสงเวทมนตร์ขึ้นฟ้าเปิดข้อความลับ', icon: 'brightness_high', from: '#10B981', to: '#18181B', bg: '#09090B', particle: 'none', tier: 'premium' },
  { id: 'mountfuji', part: 2, name: 'Mount Fuji Sunrise', nameTh: 'ฟูจิซัง รุ่งอรุณ', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'กดลั่นระฆังที่เสาโทริอิ เรียกพรแห่งแสงอรุณแรกของวันเพื่อเผยข้อความมงคลแบบญี่ปุ่น', icon: 'volcano', from: '#FCA5A5', to: '#1E1B4B', bg: '#1E293B', particle: 'none', tier: 'premium' },
  { id: 'bigben', part: 1, name: 'Big Ben Midnight', nameTh: 'หอนาฬิกาบิ๊กเบน', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'หมุนเข็มนาฬิกาบิ๊กเบนให้ถึงเที่ยงคืน เสียงระฆังดังกังวานพัดหมอกจางหายเจอข้อความผู้ดีอังกฤษ', icon: 'schedule', from: '#D4D4D8', to: '#1E293B', bg: '#78716C', particle: 'none', tier: 'premium' },
  { id: 'riodejaneiro', part: 3, name: 'Rio Carnival', nameTh: 'คาร์นิวัล ริโอเดจาเนโร', category: 'landmark', categoryTh: 'แลนด์มาร์คบรรลือโลก', desc: 'คลิกรูปปั้นพระเยซูคริสต์รับแดดยามเย็น พลุและกระดาษสีคาร์นิวัลระเบิดเต็มซอยมอบความสุข', icon: 'celebration', from: '#4ADE80', to: '#701A75', bg: '#38BDF8', particle: 'none', tier: 'premium' },

  // Category 8: 🌊 ศิลปะวิจิตร Fluid (Fluid/Art)
  { id: 'goeyliquid', part: 1, name: 'Goey Liquid Art', nameTh: 'หยดน้ำหมึกศิลปะ', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'ลากนิ้วปาดน้ำหมึกสีบนจอกระจายตัวอย่างอิสระ ก่อนกดให้มันระเบิดตัวออกเผยข้อความสุดอาร์ต', icon: 'format_paint', from: '#3B82F6', to: '#1E3A8A', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'colormagicsmoke', part: 1, name: 'Magic Colorful Smoke', nameTh: 'ควันเวทมนตร์หลากสี', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'แตะลูกแก้วกลางจอให้ระเบิดออก กลายเป็นควันเวทมนตร์หลายสีฟุ้งกระจาย ซ่อนข้อความลึกลับหรูหรา', icon: 'blur_on', from: '#D946EF', to: '#020617', bg: '#020617', particle: 'none', tier: 'premium' },
  { id: 'sinewaves', part: 3, name: 'Neon Sine Waves', nameTh: 'คลื่นความถี่นีออน', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'คลื่นเสียงหลากสีเต้นยึกยือ พอกดปุ่มจะซิงค์คลื่นให้เรียบตรงเปล่งแสงจ้า พร้อมกลายเป็นตัวหนังสือดิจิทัล', icon: 'graphic_eq', from: '#0284C7', to: '#C084FC', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'inkbleed', part: 2, name: 'Ink Bleed Poetry', nameTh: 'พู่กันหมึกซึม', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'ใช้ปลายนิ้ววาดพู่กันหมึกดำลงบนกระดาษสา ระบายไปเรื่อยๆ จนหมึกซึมหลอมรวมเป็นบทกวีของคุณ', icon: 'draw', from: '#FAFAFA', to: '#18181B', bg: '#FAFAFA', particle: 'none', tier: 'premium' },
  { id: 'holographic', part: 2, name: 'Holographic Fluid', nameTh: 'ของเหลวโฮโลแกรม', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'ก้อนกราฟิกโฮโลแกรมเรืองแสง 3D ขยับไปมา พอกดแตะจะขยายครอบคลุมทั้งจอ เผยข้อความบนกระจกฝ้าหน้าสั่น', icon: 'gradient', from: '#EC4899', to: '#14B8A6', bg: '#1E1B4B', particle: 'none', tier: 'premium' },
  { id: 'liquidmetal', part: 2, name: 'Liquid Metal', nameTh: 'ปรอทโละหะเหลว', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'หยดปรอทโลหะโครเมียมสะท้อนแสงกระจายตัว พอกดจะดูดรวมกันเป็นก้อนใหญ่แล้วระเบิดเป็นแสง เผยข้อความดาร์กๆ ขรึมๆ', icon: 'science', from: '#94A3B8', to: '#000000', bg: '#27272A', particle: 'none', tier: 'premium' },
  { id: 'watercolor', part: 3, name: 'Watercolor Splash', nameTh: 'สีน้ำกระเซ็น', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'กดปุ๊บสีน้ำพาสเทลกระเด็นเปรอะเต็มหน้าจอกระดาษ เผยให้เห็นข้อความเขียนแบบลายมือด้วยพู่กันน่ารักๆ', icon: 'brush', from: '#F472B6', to: '#38BDF8', bg: '#FAFAFA', particle: 'none', tier: 'premium' },
  { id: 'oilpaint', part: 2, name: 'Oil Paint Swirl', nameTh: 'สีน้ำมันหมุนวน', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'มวลสีน้ำมันหมุนวนผสานกันเหมือนภาพวาดแวนโก๊ะ พอกดสีจะเรืองแสงพร้อมข้อความสุดหรูสไตล์แกลลอรี่', icon: 'palette', from: '#F43F5E', to: '#8B5CF6', bg: '#000000', particle: 'none', tier: 'premium' },
  { id: 'lavalamp', part: 2, name: 'Lava Lamp', nameTh: 'โคมไฟลาวา', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'หยดลาวาเรืองแสงลอยขึ้นลง แตะเพื่อเปิดไฟโคมไฟให้สว่างอุ่น เผยให้เห็นข้อความน่ารักๆ ในฟองอากาศ', icon: 'lightbulb', from: '#F43F5E', to: '#EC4899', bg: '#0F172A', particle: 'none', tier: 'premium' },
  { id: 'plasmaball', part: 2, name: 'Plasma Ball', nameTh: 'ลูกแก้วพลาสม่า', category: 'fluid', categoryTh: 'ศิลปะวิจิตร Fluid', desc: 'ลูกแก้วช็อตไฟฟ้า สายฟ้าวิ่งตามการขยับเมาส์ พอกดลูกแก้วจะสว่างจ้าวโอเวอร์โหลด ระเบิดข้อความล้ำๆ แบบไซไฟออกมา', icon: 'electric_bolt', from: '#C084FC', to: '#38BDF8', bg: '#0F172A', particle: 'none', tier: 'premium' },

  // Category 9: 🎃 เทศกาลสุดยอด 3D (holiday3d)
  { id: 'christmas3d', part: 1, name: 'Christmas Pop-up Book', nameTh: 'หนังสือนิทานคริสต์มาส', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'คลิกเพื่อเปิดหนังสือนิทานป๊อปอัพ ต้นคริสต์มาส 3D เด้งขึ้นมากลางจอ หิมะตกปรอยๆ พร้อมข้อความอวยพร', icon: 'park', from: '#1E1B4B', to: '#B91C1C', bg: '#0F172A', particle: 'none', tier: 'premium' },
  { id: 'halloween3d', part: 2, name: 'Halloween Haunted 3D', nameTh: 'บ้านผีสิง 3D', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'เคาะประตูบ้านร้างสุดหลอน ประตูเปิดแง้มออก 3D วิญญาณพุ่งทะลุจอมาหาคุณ! พร้อมข้อความเขย่าขวัญ', icon: 'sentiment_very_dissatisfied', from: '#27272A', to: '#EA580C', bg: '#050505', particle: 'none', tier: 'premium' },
  { id: 'valentine3d', part: 3, name: '3D Valentine Heart Box', nameTh: 'กล่องหัวใจ 3D', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'กล่องของขวัญวาเลนไทน์หมุน 3D พอกดปุ๊บฝาปลิวเปิดออก หัวใจนับร้อยพุ่งกระจาย พร้อมคำบอกรักสุดหวาน', icon: 'favorite', from: '#FFE4E6', to: '#BE123C', bg: '#F43F5E', particle: 'none', tier: 'premium' },
  { id: 'songkran', part: 3, name: 'Songkran Splash', nameTh: 'สงกรานต์สาดน้ำ', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'กดยิงปืนฉีดน้ำ สาดน้ำกระเซ็นติดหน้าจอโทรศัพท์ น้ำย้อยลงมาเผยให้เห็นคำอวยพรวันสงกรานต์', icon: 'water_drop', from: '#BAE6FD', to: '#0284C7', bg: '#0EA5E9', particle: 'none', tier: 'premium' },
  { id: 'loykrathong', part: 2, name: 'Loy Krathong 3D', nameTh: 'ลอยกระทง 3 มิติ', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'ริมแม่น้ำใต้แสงจันทร์ กดที่กระทงเพื่อจุดไฟ กระทงจะลอยออกไปไกลๆ พร้อมโคมลอยเต็มฟ้าและข้อความอธิษฐาน', icon: 'waves', from: '#020617', to: '#FACC15', bg: '#1E3A8A', particle: 'none', tier: 'premium' },
  { id: 'chinesenewyear', part: 1, name: 'Lunar New Envelope', nameTh: 'ตรุษจีนอั่งเปา 3D', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'ซองอั่งเปา 3D หมุนได้ พอกดเปิดซอง เหรียญทองจะกระเด็นออกพร้อมป้ายคำอวยพรมงคลสไตล์จีน', icon: 'celebration', from: '#FEF08A', to: '#DC2626', bg: '#7F1D1D', particle: 'none', tier: 'premium' },
  { id: 'easter3d', part: 1, name: 'Easter Egg Hunt', nameTh: 'ค้นหาไข่อีสเตอร์ 3D', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'ไข่ยักษ์ 3D ตั้งอยู่กลางทุ่งหญ้า กดกะเทาะเปลือกไข่ให้แตกเพื่อพบกับข้อความเซอร์ไพรส์และพลุกระดาษ', icon: 'egg', from: '#FBCFE8', to: '#4ADE80', bg: '#166534', particle: 'none', tier: 'premium' },
  { id: 'diwali', part: 1, name: 'Diwali Festival', nameTh: 'เทศกาลทิวาลี', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'จุดไฟตะเกียงดินเผา (Diya) พื้นจะสว่างขึ้นเผยให้เห็นลวดลายรังโกลี พร้อมแสงวิบวับพุ่งขึ้นฟ้า', icon: 'local_fire_department', from: '#FFEDD5', to: '#EA580C', bg: '#450A0A', particle: 'none', tier: 'premium' },
  { id: 'thanksgiving', part: 3, name: 'Thanksgiving Dinner', nameTh: 'อาหารมื้อค่ำขอบคุณพระเจ้า', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'จานอาหารหรูครอบฝาเงิน 3D พอกดเปิดฝาจะบินออก เผยให้เห็นไก่งวงพร้อมข้อความขอบคุณสุดซึ้ง', icon: 'restaurant_menu', from: '#FEF3C7', to: '#D97706', bg: '#451A03', particle: 'none', tier: 'premium' },
  { id: 'newyearcountdown', part: 2, name: 'New Year Countdown', nameTh: 'เคาท์ดาวน์ปีใหม่ 3D', category: 'holiday3d', categoryTh: 'เทศกาลสุดยอด 3D', desc: 'ลูกบอลกระจก 3D ห้อยลงมา พอกดจะเริ่มนับถอยหลัง 3..2..1! แล้วระเบิดเป็นพลุฉลองปีใหม่ตระการตา', icon: 'nightlife', from: '#FACC15', to: '#1E293B', bg: '#020617', particle: 'none', tier: 'premium' },

  // Category 10: 💎 หรูหรา ไฮโซอุดมคติ (luxury)
  { id: 'diamondreveal', part: 1, name: 'Diamond Reveal', nameTh: 'เปิดเผยเพชร 3D', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'เพชรเจียระไน 3D สีรุ้งล่องลอยอยู่กลางจอ พอกดปุ๊บมันหมุน 720 องศา เรืองแสงจ้าแล้วระเบิดเผยข้อความสไตล์เพชรพรายสุดพรีเมียม', icon: 'diamond', from: '#A8EDEA', to: '#FED6E3', bg: '#0F0C29', particle: 'none', tier: 'premium' },
  { id: 'goldvault', part: 2, name: 'Gold Bullion Vault', nameTh: 'ห้องนิรภัยทองคำ', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'ประตูห้องนิรภัยเหล็กหนาขนาดใหญ่ กดหมุนวงล้อกลไกแล้วประตูจะบานออก เผยให้เห็นทองคำแท่งกองสูง พร้อมข้อความสลักบนทอง', icon: 'savings', from: '#FDE047', to: '#78350F', bg: '#16213E', particle: 'none', tier: 'premium' },
  { id: 'champagne', part: 1, name: 'Champagne Shower', nameTh: 'แชมเปญฉลอง', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'ขวดแชมเปญสีนาวีตั้งอยู่ใต้แสงสปอตไลท์ พอกดขวดจะสั่นระรัก คอร์กพุ่งออก น้ำแชมเปญฉีดพ่นระเบิดพร้อมฟองละเอียดลอยขึ้นเต็มจอ', icon: 'wine_bar', from: '#FDE047', to: '#1E3A5F', bg: '#0D0D0D', particle: 'none', tier: 'premium' },
  { id: 'vipvelvet', part: 3, name: 'VIP Velvet Curtain', nameTh: 'ม่านกำมะหยี่ VIP', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'ม่านกำมะหยี่แดงสด ริมขอบทอง พรมแดงปูบนพื้น แสงสปอตไลท์ส่าย พอกดม่านจะค่อยๆ เปิดออก เผยให้เห็นข้อความ VIPสุดอลังการ', icon: 'theater_comedy', from: '#FDE047', to: '#7F1D1D', bg: '#0A0A0A', particle: 'none', tier: 'premium' },
  { id: 'sportcardrift', part: 3, name: 'Sports Car Drift', nameTh: 'รถสปอร์ตดริฟต์', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'รถสปอร์ตสีแดงจอดรอบนสนาม พอกดรถจะออกตัวดริฟต์ข้ามจอ ยางลากพื้นทิ้งรอยควันไหม้ ก่อนระเบิดออกเป็นข้อความที่ตะโกนบอก', icon: 'directions_car', from: '#DC2626', to: '#09090B', bg: '#09090B', particle: 'none', tier: 'premium' },
  { id: 'privatejet', part: 3, name: 'Private Jet Banner', nameTh: 'แบนเนอร์เครื่องบินส่วนตัว', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'เครื่องบิน CSS 3D บินเข้ามาจากซ้าย ลากแบนเนอร์ผ้าด้านหลังที่เขียนชื่อผู้รับ บินผ่านเมฆสีชมพูพระอาทิตย์ตกกันชัดๆ', icon: 'flight', from: '#FF4C29', to: '#082032', bg: '#082032', particle: 'none', tier: 'premium' },
  { id: 'luxurywatch', part: 2, name: 'Luxury Watch Unbox', nameTh: 'เปิดกล่องนาฬิกาหรู', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'กล่องนาฬิกาหรูสีดำกำมะหยี่ กดเปิดฝาออก นาฬิกาหน้าทองค่อยๆ ลอยขึ้นมาพร้อมแสงสะท้อน เข็มหมุนอยู่บอกเวลายาวนาน', icon: 'watch', from: '#D4AF37', to: '#1C1C1E', bg: '#000', particle: 'none', tier: 'premium' },
  { id: 'caviartin', part: 1, name: 'Caviar Tin', nameTh: 'กระป๋องคาเวียร์', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'กระป๋องคาเวียร์หรูสีดำขอบทองวางบนโต๊ะหินอ่อน กดเปิดฝาเพื่อเผยเม็ดคาเวียร์เป็นพันเม็ด พร้อมช้อนมุกสวยงามและข้อความสุดพรีเมียม', icon: 'restaurant', from: '#FDE047', to: '#1A1A1A', bg: '#0A0A0A', particle: 'none', tier: 'premium' },
  { id: 'penthouse', part: 2, name: 'Penthouse Night View', nameTh: 'วิวคืนจากเพนท์เฮาส์', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'บรรยากาศเพนท์เฮาส์ชั้น 80 ยามค่ำ วิวตึกระฟ้าไฟสว่างทั่วเมือง พระจันทร์เต็มดวง กดแก้วไวน์เพื่อเผย ข้อความสุดโรแมนติก', icon: 'apartment', from: '#FDE68A', to: '#0A0A23', bg: '#0A0A0A', particle: 'none', tier: 'premium' },
  { id: 'royalmedal', part: 3, name: 'Royal Gold Medallion', nameTh: 'เหรียญทองราชวงศ์', category: 'luxury', categoryTh: 'หรูหรา V.I.P Showcase', desc: 'เหรียญทองคำราชวงศ์หมุนลอยอยู่กลางจอ มีมงกุฏประดับด้านใน กดแตะเหรียญให้หมุน 720° แล้วระเบิดพ่นแสงเผยพระราชสาส์นสุดอลัง', icon: 'military_tech', from: '#FDE047', to: '#1C0A00', bg: '#0D0600', particle: 'none', tier: 'premium' }
];
